version: "3"

output: prefixed

env:
  CGO_ENABLED: 0
  LD_FLAGS: -s -w -X main.version={{.VERSION}}

tasks:
  diff:
    desc: Run diff
    cmds:
      - go run cmd/main.go diff --db ./examples/test.db -s ./examples/schema/

  # 󰚰 Update deps
  update:
    desc: Update dependencies
    cmds:
      - go get -u ./...

  # 󰉠  Lint / static checks
  lint:
    desc: Run go vet & lint
    cmds:
      - go mod tidy
      - go fmt ./...
      - go vet ./...
      - go test ./...

  build:
    desc: Build binary
    cmds:
      - go build -ldflags "{{.LD_FLAGS}}" -o sqlite-schema-diff ./cmd/

  snapshot:
    desc: Test snapshot
    cmds:
      - goreleaser --snapshot --clean --skip=validate

  release:
    desc: Test release
    cmds:
      - goreleaser --release --clean
