version: "3"

tasks:
  diff:
    desc: Run diff
    cmds:
      - go run . diff --db ./examples/example.db -s ./examples/schema/

  apply:
    desc: Run apply
    cmds:
      - go run . apply --db ./examples/example.db -s ./examples/schema/

  examples:
    desc: Run examples
    dir: examples
    cmds:
      - go run .

  update:
    desc: Update dependencies
    cmds:
      - go get -u ./...

  lint:
    desc: Run go vet & lint
    cmds:
      - go mod tidy
      - go fmt ./...
      - go vet ./...
      - gofumpt -w .
      - golines -w .
      - govulncheck ./...
      - go test -race -count=1 -cover ./...
      - golangci-lint run

  coverage:
    desc: Run coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  build:
    desc: Build binary
    cmds:
      - go build -ldflags="-s -w" -trimpath -o sqlite-schema-diff

  snapshot:
    desc: Build snapshot
    cmds:
      - goreleaser --snapshot --clean --skip=validate,sign,sbom,archive
