package diff

import (
	"database/sql"
	"fmt"
	"strings"

	"github.com/mizuchilabs/sqlite-schema-diff/pkg/parser"
)

// Compare compares a database against a schema directory and returns changes.
// If SetBaseFS was called, reads from the embedded filesystem instead.
func Compare(db *sql.DB, schemaDir string) ([]Change, error) {
	current, err := parser.FromDB(db)
	if err != nil {
		return nil, err
	}

	target, err := parser.ReadFiles(schemaDir)
	if err != nil {
		return nil, err
	}

	return Diff(current, target), nil
}

// CompareDatabases compares two databases
func CompareDatabases(from, to *sql.DB) ([]Change, error) {
	fromSchema, err := parser.FromDB(from)
	if err != nil {
		return nil, err
	}

	toSchema, err := parser.FromDB(to)
	if err != nil {
		return nil, err
	}

	return Diff(fromSchema, toSchema), nil
}

// GenerateSQL generates a complete migration script
func GenerateSQL(changes []Change) string {
	if len(changes) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("-- Generated by sqlite-schema-diff\n")
	sb.WriteString("PRAGMA foreign_keys = OFF;\n")
	sb.WriteString("BEGIN TRANSACTION;\n\n")

	for _, c := range changes {
		fmt.Fprintf(&sb, "-- %s: %s\n", c.Type, c.Description)

		for _, stmt := range c.SQL {
			sb.WriteString(stmt)
			sb.WriteString("\n")
		}

		sb.WriteString("\n")
	}

	sb.WriteString("COMMIT;\n")
	sb.WriteString("PRAGMA foreign_keys = ON;\n")
	return sb.String()
}
