package diff

import (
	"context"
	"database/sql"
	"fmt"
	"io/fs"
	"strings"

	"github.com/mizuchilabs/sqlite-schema-diff/pkg/parser"
)

// Compare compares a database against the .sql files in fsys and returns
// the changes needed to make the database match them. Use [os.DirFS] for a
// directory on disk, or [fs.Sub] to point an [embed.FS] at the schema
// directory.
func Compare(ctx context.Context, db *sql.DB, fsys fs.FS) ([]Change, error) {
	target, err := parser.ReadFiles(ctx, fsys)
	if err != nil {
		return nil, err
	}

	current, err := parser.FromDB(ctx, db)
	if err != nil {
		return nil, err
	}

	return Diff(current, target), nil
}

// CompareDatabases compares two databases.
func CompareDatabases(ctx context.Context, from, to *sql.DB) ([]Change, error) {
	fromSchema, err := parser.FromDB(ctx, from)
	if err != nil {
		return nil, err
	}

	toSchema, err := parser.FromDB(ctx, to)
	if err != nil {
		return nil, err
	}

	return Diff(fromSchema, toSchema), nil
}

// GenerateSQL generates a complete migration script.
func GenerateSQL(changes []Change) string {
	if len(changes) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("-- Generated by sqlite-schema-diff\n")
	sb.WriteString("PRAGMA foreign_keys = OFF;\n")
	sb.WriteString("PRAGMA legacy_alter_table = ON;\n")
	sb.WriteString("BEGIN TRANSACTION;\n\n")

	for _, c := range changes {
		fmt.Fprintf(&sb, "-- %s: %s\n", c.Type, c.Description)

		for _, stmt := range c.SQL {
			sb.WriteString(stmt)
			sb.WriteString("\n")
		}

		sb.WriteString("\n")
	}

	sb.WriteString("COMMIT;\n")
	sb.WriteString("PRAGMA legacy_alter_table = OFF;\n")
	sb.WriteString("PRAGMA foreign_keys = ON;\n")
	return sb.String()
}
